# Generated by Django 4.1 on 2022-09-02 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_category_product"),
    ]

    operations = [
        migrations.RemoveField(model_name="products", name="categoryId",),
        migrations.AlterField(
            model_name="product",
            name="categoryId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.category"
            ),
        ),
        migrations.DeleteModel(name="Categories",),
        migrations.DeleteModel(name="Products",),
    ]
