# Generated by Django 4.1 on 2022-10-07 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reviewDescription",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="reviewName",
            field=models.CharField(default="", max_length=225),
        ),
        migrations.AddField(
            model_name="review",
            name="reviewedDate",
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
